stages:
  - build
  - deploy

variables:
  DIST: bullseye
  DEPS: >-
    ccache build-essential libgtk-3-dev libcallaudio-dev libhandy-1-dev meson
    python3-toml python3-jinja2 python3-typogrify libgirepository1.0-dev git
  EXP_DEPS: libhandy-1-dev/experimental libhandy-1-0/experimental gir1.2-handy-1/experimental libgladeui-common/experimental

before_script:
  - echo "man-db man-db/auto-update boolean false" | debconf-set-selections
  - export DEBIAN_FRONTEND=noninteractive
  - echo "deb http://deb.debian.org/debian/ experimental main" > /etc/apt/sources.list.d/exp.list
  - apt-get -y update
  - apt-get -y install eatmydata
  - eatmydata apt-get -y install $DEPS
  - eatmydata apt-get -y install $EXP_DEPS

.build: &build_steps
    echo "BUILD_OPTS=${BUILD_OPTS}" &&
    export LC_ALL=C.UTF-8 &&
    meson ${BUILD_OPTS} . _build  &&
    ninja -C _build

build-debian-gcc:
  image: debian:bullseye
  stage: build
  variables:
    BUILD_OPTS: --werror
  script:
    - *build_steps
  artifacts:
    when: always
    paths:
      - _build

# TODO: move to prebuilt container
doc:
  image: debian:bullseye
  stage: build
  variables:
    BUILD_OPTS: >-
      -Dtests=false
      -Dgtk_doc=true
  script:
    - meson ${BUILD_OPTS} _build
    - ninja -C _build
    - mv _build/doc/libcall-ui-0 _doc/
  artifacts:
    paths:
      - _doc/

pages:
  stage: deploy
  before_script: []
  needs: ['doc']
  script:
    - mv _doc/ public/
  artifacts:
    paths:
      - public
  only:
    - main
